### PR TITLE
Fixed link detection to not fail when there's a . or - in the URL

### PR DESCRIPTION
**Pull request by brandenr**

### CODE REVIEW

**Comment by nickmshelley** [comment]
Test?

**Comment by brandenr** [comment]
Hm. How do I create a test for being able to tap a link?

**Comment by nickmshelley** [comment]
Sorry I'm not super familiar with the bug, but is this something that can be unit tested? Maybe just put some text somewhere and make sure there's a link attribute?

**Comment by brandenr** [comment]
I think I've figured out a few tests to write and have found a bug in the markdownString() and another bug in link detection to fix as well because of the tests

**Comment by nickmshelley** [comment]
Yay, nice work!

**Review by SerenadeX — APPROVED** [review]

**Pull request merged**
